# Generated by Django 5.2.14 on 2026-06-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Selecao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("sigla", models.CharField(max_length=3, unique=True)),
                ("grupo", models.CharField(max_length=1)),
                ("bandeira_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
