# Generated by Django 5.2.14 on 2026-06-05 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bolao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField()),
                ("gols_casa", models.IntegerField(blank=True, null=True)),
                ("gols_fora", models.IntegerField(blank=True, null=True)),
                (
                    "fase",
                    models.CharField(
                        choices=[
                            ("GRUPOS", "Fase de Grupos"),
                            ("OITAVAS", "Oitavas de Final"),
                            ("QUARTAS", "Quartas de Final"),
                            ("SEMI", "Semifinal"),
                            ("FINAL", "Final"),
                        ],
                        default="GRUPOS",
                        max_length=20,
                    ),
                ),
                (
                    "selecao_casa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogos_como_casa",
                        to="bolao.selecao",
                    ),
                ),
                (
                    "selecao_fora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogos_como_fora",
                        to="bolao.selecao",
                    ),
                ),
            ],
        ),
    ]
