# Generated by Django 5.2.14 on 2026-06-07 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bolao", "0003_palpite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="palpite",
            options={"verbose_name": "Palpite", "verbose_name_plural": "Palpites"},
        ),
        migrations.RemoveField(
            model_name="palpite",
            name="criado_em",
        ),
        migrations.RemoveField(
            model_name="palpite",
            name="gols_palpite_casa",
        ),
        migrations.RemoveField(
            model_name="palpite",
            name="gols_palpite_fora",
        ),
        migrations.AddField(
            model_name="palpite",
            name="data_atualizacao",
            field=models.DateTimeField(auto_now=True, verbose_name="Última alteração"),
        ),
        migrations.AddField(
            model_name="palpite",
            name="gols_casa",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Gols Casa (Palpite)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="palpite",
            name="gols_fora",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Gols Fora (Palpite)"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="palpite",
            name="jogo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="palpites",
                to="bolao.jogo",
                verbose_name="Jogo",
            ),
        ),
        migrations.AlterField(
            model_name="palpite",
            name="pontos_ganhos",
            field=models.IntegerField(default=0, verbose_name="Pontos Ganhos"),
        ),
        migrations.AlterField(
            model_name="palpite",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="palpites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Palpiteiro",
            ),
        ),
    ]
