# Generated by Django 5.2.14 on 2026-06-07 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bolao", "0004_alter_palpite_options_remove_palpite_criado_em_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jogo",
            name="fase",
            field=models.CharField(
                choices=[
                    ("GRUPOS", "Fase de Grupos"),
                    ("OITAVAS", "Oitavas de Final"),
                    ("QUARTAS", "Quartas de Final"),
                    ("SEMIFINAL", "Semifinal"),
                    ("TERCEIRO", "Disputa de 3º Lugar"),
                    ("FINAL", "Final"),
                ],
                default="GRUPOS",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="palpite",
            name="jogo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="palpites_do_jogo",
                to="bolao.jogo",
                verbose_name="Jogo",
            ),
        ),
    ]
