# Generated by Django 5.2.14 on 2026-06-08 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bolao", "0005_alter_jogo_fase_alter_palpite_jogo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jogo",
            name="fase",
            field=models.CharField(
                choices=[
                    ("GRUPOS", "Fase de Grupos"),
                    ("16 Avos", "16 Avos de Final"),
                    ("OITAVAS", "Oitavas de Final"),
                    ("QUARTAS", "Quartas de Final"),
                    ("SEMIFINAL", "Semifinal"),
                    ("TERCEIRO", "Disputa de 3º Lugar"),
                    ("FINAL", "Final"),
                ],
                default="GRUPOS",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jogo",
            name="selecao_casa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jogos_como_casa",
                to="bolao.selecao",
            ),
        ),
        migrations.AlterField(
            model_name="jogo",
            name="selecao_fora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jogos_como_fora",
                to="bolao.selecao",
            ),
        ),
    ]
