# Generated by Django 5.2.14 on 2026-06-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bolao", "0006_alter_jogo_fase_alter_jogo_selecao_casa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogo",
            name="numero_jogo",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
